### ISSUE TITLE
Refactor into classes

### ISSUE THREAD

**Issue by chrehall68** [SJSURoboticsTeam/urc-intelligent-systems-2023#125]
# Issue:
part of #114 
* get rid of global variables in files like `captain.py` since these global variables are often scattered around the file, making files unorganized. Also, these global variables might instantiate items that we shouldn't be instantiating if the name isn't main. Instead, use classes with instance variables
* Export classes, not modules for ease-of-use

**Comment by RK22000** [comment]
Files to Refactor
==========
- [x] unified_frameworks\sensor_array\lidar.py
- [x] unified_frameworks\worldview.py
- [x] unified_frameworks\pathfinder.py
- [x] unified_frameworks\captain.py

Gonna refactor them all as types of Service (class in unified_utils)
