### ISSUE TITLE
ArUco marker Detection

### ISSUE THREAD

**Issue by acarrou** [SJSURoboticsTeam/urc-intelligent-systems-2023#14]
We will need to develop something in OpenCV and Python or other to find the required ArUco markers for this autonomy navigation part of the competition.
<img width="377" alt="image" src="https://user-images.githubusercontent.com/50222631/201214033-9b329be5-d924-47d8-a6cb-204a188469a7.png">

**Comment by JVP15** [comment]
Implemented basic Aruco tag detection in `jordan-aruco-detection` branch.

**Comment by acarrou** [comment]
currently in the testing phase
