### ISSUE TITLE
Obstacle Avoidance

### ISSUE THREAD

**Issue by acarrou** [SJSURoboticsTeam/urc-intelligent-systems-2023#17]
The rover needs some way to avoid obstacles when we run the central autonomous drive system. This will involve different sensors such as lidar, cameras, and potentially more. We want to stay away from ROS and stick with python as this is what we have been working with for autonomous driving. The idea is to re-path the rover to the GPS coordinate when there is an obstruction.

**Comment by acarrou** [comment]
Lidar is being worked on with #53 and #54 but still needs to implement point cloud with the camera.

**Comment by acarrou** [comment]
@ElaynaSeguin @dontario Main needs to be tested for object detection. Use the ObjectDetector.py class and make a demo.

**Comment by chrehall68** [comment]
We have pivoted to something similar to this with the newest revision of the repository.
