### ISSUE TITLE
Verifying Aruco Tag Detector code

### ISSUE THREAD

**Issue by Maaz0070** [SJSURoboticsTeam/urc-intelligent-systems-2023#71]
## GitHub Issue: Aruco Tag Detection Test

**Description:**
The current code contains an implementation for detecting Aruco tags using the OAK-D Lite camera. We need to test the functionality of this code on the `jordan-aruco-detection` branch to ensure it correctly detects Aruco tags when the OAK-D Lite camera is plugged in.

**Steps to Test:**

1. Clone the repository and create a branch off of the `jordan-aruco-detection` branch:
```
git clone <repository_url>
cd <repository_name>
git checkout jordan-aruco-detection
```

2. Set up the OAK-D Lite camera and ensure it is correctly connected to the system.

3. Install the required dependencies, including those already mentioned in the `requirements.txt` file, and additional dependencies for the Aruco Tag Detection module and the OpenCV library:
```
pip install opencv-python-headless
```
4. Execute the provided script test_aruco_detection.py containing the Aruco tag detection code.

Expected Outcome:

The script should run without errors, utilizing the OAK-D Lite camera to capture images for Aruco tag detection.
When an Aruco tag is present in the camera's field of view, the script should draw the tag's outline and display its ID on the image.
The script should continue to run and detect Aruco tags until the user presses the 'q' key to exit.

**Comment by chrehall68** [comment]
Working aruco detection is on maaz aruco detection branch
