### ISSUE TITLE
Aruco Tag detector Mission Script for Testing

### ISSUE THREAD

**Issue by Maaz0070** [SJSURoboticsTeam/urc-intelligent-systems-2023#83]
# Test and Integrate ArucoDetector with GPS_Nav

## Description
  This issue addresses the integration and testing of the ArucoDetector code with the GPS_Nav functionality. We will develop a Mission script based on the `Missions/aruco.py` script in the `maaz-aruco-detection` branch to test the combined functionality.

---

## Issue Description

**Background:**

Our project involves rover navigation using GPS coordinates and Aruco tag detection. The ArucoDetector code and GPS_Nav features have been developed independently and need to be integrated and thoroughly tested to ensure they work seamlessly together. Additionally, a Mission script needs to be developed to evaluate the combined functionality.

**Objectives:**

1. Test the functionality of the ArucoDetector code in conjunction with the GPS_Nav features.
2. Develop a Mission script based on the provided `Missions/aruco.py` script to demonstrate the integrated functionality.

**Tasks:**

1. **Integration of ArucoDetector and GPS_Nav:**
   - Ensure that the ArucoDetector code is correctly integrated into the GPS_Nav class.
   - Verify that the GPS_Nav class effectively calls the ArucoDetector's methods when necessary (e.g., when searching for Aruco tags).

2. **Testing Scenarios:**
   - Develop a set of test scenarios that represent common navigation scenarios for the rover, as outlined in the provided `Missions/aruco.py` script.
   - Include scenarios such as navigating to specific GPS coordinates, initiating spinning until an Aruco tag is detected, handling cases where Aruco tags are not detected, and transitioning between modes (e.g., drive, spin, and translate).

3. **Mission Script Development:**
   - Expand the Mission script (e.g., Missions/aruco.py) that defines and executes the test scenarios as specified.
   - Ensure that the Mission script is based on the provided `Missions/mission.py` script.

4. **Testing and Validation:**
   - Execute the Mission script and observe the rover's behavior in various scenarios.
   - Verify that the rover navigates accurately to GPS coordinates.
   - Confirm that the rover successfully detects Aruco tags and responds accordingly.
   - Ensure that the rover transitions between modes as expected.
   - Log and report any issues, unexpected behavior, or errors encountered during testing.

5. **Documentation:**
   - Update relevant documentation, including README files, to reflect the integrated functionality and provide instructions on running the Mission script.

**Expected Outcome:**

Upon completion of this issue, we expect to have a fully integrated and tested system that combines GPS-based navigation and Aruco tag detection. The Mission script should demonstrate the rover's ability to navigate autonomously, including scenarios where it searches for Aruco tags and transitions between modes as needed.

**Additional Information:**

- Relevant code files: ArucoDetector.py, GPS_Nav.py, Missions/arucopy (provided).
- Dependencies: Ensure that all required dependencies are correctly installed and outlined in the appropiate requirements.txt
- Testing environment: Specify the hardware and software setup used for testing.

**Comment by chrehall68** [comment]
We are now moving to using a pathfinding service, so the requirements are now different. While this task still needs to be done in some way, the specific way specified in this issue is no longer relevant.
