### ISSUE TITLE
Object Detection for Orange Rubber Mallet

### ISSUE THREAD

**Issue by Maaz0070** [SJSURoboticsTeam/urc-intelligent-systems-2023#84]
## Issue Summary
For URC 2024 we must develop object detection functionality to autonomously locate and approach an orange rubber mallet using OpenCV or other and python:

<img src="https://m.media-amazon.com/images/I/51R11UnFvgL._AC_SL1500_.jpg" width="304" height="363">

## Issue Description
One of the objects that participating rovers need to detect and approach is an orange rubber mallet. The mallet may have varying orientations and could be positioned against a brownish orange background, making accurate detection challenging.

## Feature Requirements
The feature should include:
1. Object Detection: Accurate and reliable detection of an orange rubber mallet.
2. Background Variation: The ability to detect the mallet even when placed against a brownish orange background.
3. GNSS Integration: Integration of GNSS coordinates for precise mallet localization. The rover should be able to determine the distance to the mallet in terms of [lat, long] and command the rover to drive up to it(similar to implementation in Aruco detector)

## Acceptance Criteria
1. Successful detection and approach of the orange rubber mallet within a specified radius.
2. Reliable detection even when the mallet is positioned against a brownish orange background.
3. Accurate GNSS localization of the mallet.

## References
- [University Rover Challenge (URC) Guidelines](https://urc.marssociety.org/home/requirements-guidelines)

**Comment by chrehall68** [comment]
Completed in branch `gael-malletwater-detection`, same with #85; some code is reusable while others will need to be tweaked for URC 2025
